### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by waltsims** [waltsims/Thesis_Template_CSE#20]
This might be a little overkill, but what do @MakisH you think of something like https://buildkite.com/#features.  There is a free student version just to make sure everythig builds when merging commits.... kinda overkill but I would like to try it.  Would love your feedback.

**Comment by MakisH** [comment]
I don't know the service you are refering to, but I don't like the "there is a free student version". This could expire anytime and someone would need to set it up again.

Since we are on GitHub and on a public repository, I would go with Travis-CI (made by GitHub). I have never used it, but it looks quite popular and it is completely free for Open Source projects.

I think it is not so easy to set it up for *TeX projects, but [this looks interesting](https://github.com/harshjv/travis-ci-latex-pdf).

Although this would be very nice to play with, I don't think it is a priority in any way. We eitherways build it manually all the time and when I do major changes I also test it for pdflatex/xelatex/lualatex. As long as it doesn't create any extra problems, I am up for it. If you want to try it, do it on a different branch first.

**Comment by waltsims** [comment]
i don't think anything we're doing here is a priority 🥇
